# Generated by Django 4.0.5 on 2022-08-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='position',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Campo no rellenable'),
        ),
    ]
