# Generated by Django 4.0.5 on 2022-08-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='position',
            field=models.CharField(choices=[('isquierda', 'Isquierda'), ('derecha', 'Derecha')], default='derecha', max_length=10, verbose_name='Posicion del texto'),
        ),
    ]
