# Generated by Django 4.0.5 on 2022-08-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blog_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.CharField(help_text='Use un bot de telegram de imgur para subir las fotos y copie el enlace aqui', max_length=100, null=True, verbose_name='Imagen'),
        ),
    ]
