# Generated by Django 4.0.5 on 2022-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_imagenproducto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='imagen',
            field=models.CharField(default=1, max_length=100, verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
